#!/usr/bin/env python3
"""
train_ml_scorer.py — Train a gradient-boosted ML scorer from JSONL training
data, evaluate it, and save the model for use in collector.py.

The trained model accepts the same feature vector produced by
file_features.extract_features() and outputs a probability score in [0, 1]
indicating how likely a file is worth scanning for documentation generation.

Usage:
    # Train and save
    python3 train_ml_scorer.py train \\
        --data training_data.jsonl \\
        --model scorer.pkl \\
        [--test-split 0.2]

    # Evaluate an existing model against a JSONL file
    python3 train_ml_scorer.py eval \\
        --data training_data.jsonl \\
        --model scorer.pkl

    # Score files from stdin (one path per line) using a saved model
    python3 train_ml_scorer.py score \\
        --model scorer.pkl \\
        [--top-k 50] \\
        [--threshold 0.5]
    # e.g.: git ls-files | python3 train_ml_scorer.py score --model scorer.pkl

Dependencies:
    pip install scikit-learn --break-system-packages
"""

import argparse
import json
import pickle
import sys
from pathlib import Path

from model.file_features import FEATURE_COLUMNS, extract_features, features_to_vector

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_jsonl(path: str) -> tuple[list, list, list]:
    """
    Read a JSONL file produced by generate_training_data.py.

    Returns
    -------
    X : list of feature vectors (list of float)
    y : list of int labels (0 or 1)
    meta : list of dicts with "repo", "path", "source", "reason"
    """
    X, y, meta = [], [], []
    with open(path, encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as e:
                print(f"⚠️ Skipping malformed line {lineno}: {e}", file=sys.stderr)
                continue

            feats = record.get("features")
            label = record.get("label")
            if feats is None or label not in (0, 1):
                continue

            # Re-extract from path if stored features are missing columns
            # (handles data generated by an older version of file_features.py)
            if not all(col in feats for col in FEATURE_COLUMNS):
                feats = extract_features(record["path"])

            X.append(features_to_vector(feats))
            y.append(int(label))
            meta.append({
                "repo":   record.get("repo", ""),
                "path":   record.get("path", ""),
                "source": record.get("source", ""),
                "reason": record.get("reason", ""),
            })

    return X, y, meta


# ---------------------------------------------------------------------------
# Model: Gradient Boosted Trees via sklearn
# ---------------------------------------------------------------------------

def _build_pipeline():
    """Build a GradientBoostingClassifier pipeline.

    GBT is chosen over a simple logistic regression because:
    - Feature interactions matter (e.g. in_examples AND ext_group_code > each alone)
    - No need to scale features manually
    - Still small and fast at this feature dimensionality (18 features)
    """
    from sklearn.ensemble import GradientBoostingClassifier
    from sklearn.pipeline import Pipeline

    return Pipeline([
        ("clf", GradientBoostingClassifier(
            n_estimators=200,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            random_state=42,
        )),
    ])


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def cmd_train(data_path: str, model_path: str, test_split: float):
    try:
        from sklearn.model_selection import train_test_split
        from sklearn.metrics import classification_report, roc_auc_score
    except ImportError:
        print("❌ scikit-learn not installed.\n"
              "   Run: pip install scikit-learn --break-system-packages", file=sys.stderr)
        sys.exit(1)

    print(f"📂 Loading training data from {data_path} ...")
    X, y, meta = load_jsonl(data_path)

    if len(X) == 0:
        print("❌ No valid records found in training data.", file=sys.stderr)
        sys.exit(1)

    n_pos = sum(y)
    n_neg = len(y) - n_pos
    print(f"   {len(X)} samples  |  include={n_pos}  exclude={n_neg}  "
          f"({n_pos / len(y) * 100:.1f}% positive)")

    if test_split > 0:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=test_split, random_state=42, stratify=y
        )
    else:
        X_train, y_train = X, y
        X_test, y_test = [], []

    print(f"\n🏋️  Training on {len(X_train)} samples ...")
    pipeline = _build_pipeline()
    pipeline.fit(X_train, y_train)

    if X_test:
        print("\n📊 Evaluation on held-out test set:")
        y_pred  = pipeline.predict(X_test)
        y_proba = pipeline.predict_proba(X_test)[:, 1]
        print(classification_report(y_test, y_pred, target_names=["exclude", "include"]))
        auc = roc_auc_score(y_test, y_proba)
        print(f"   ROC-AUC: {auc:.4f}")

    # Save model
    model_data = {
        "pipeline": pipeline,
        "feature_columns": FEATURE_COLUMNS,
        "training_samples": len(X_train),
    }
    with open(model_path, "wb") as f:
        pickle.dump(model_data, f)
    print(f"\n✅ Model saved: {model_path}")

    # Print feature importances
    _print_feature_importances(pipeline)


def _print_feature_importances(pipeline):
    try:
        clf = pipeline.named_steps["clf"]
        importances = clf.feature_importances_
        pairs = sorted(zip(FEATURE_COLUMNS, importances), key=lambda x: x[1], reverse=True)
        print("\n🔍 Feature importances (top 10):")
        for name, imp in pairs[:10]:
            bar = "█" * int(imp * 40)
            print(f"  {name:<22} {imp:.4f}  {bar}")
    except AttributeError:
        pass


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def cmd_eval(data_path: str, model_path: str):
    try:
        from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
    except ImportError:
        print("❌ scikit-learn not installed.", file=sys.stderr)
        sys.exit(1)

    pipeline, _ = _load_model(model_path)
    X, y, meta = load_jsonl(data_path)

    if not X:
        print("❌ No valid records.", file=sys.stderr)
        sys.exit(1)

    y_pred  = pipeline.predict(X)
    y_proba = pipeline.predict_proba(X)[:, 1]

    print(f"\n📊 Evaluation on {len(X)} samples from {data_path}:")
    print(classification_report(y, y_pred, target_names=["exclude", "include"]))
    auc = roc_auc_score(y, y_proba)
    print(f"   ROC-AUC: {auc:.4f}")

    # Show worst mistakes (high confidence wrong predictions)
    mistakes = []
    for i, (true, pred, prob, m) in enumerate(zip(y, y_pred, y_proba, meta)):
        if true != pred:
            conf = prob if pred == 1 else 1 - prob
            mistakes.append((conf, true, pred, m["path"], m["reason"]))
    mistakes.sort(reverse=True)

    if mistakes:
        print(f"\n❌ Top 10 high-confidence mistakes:")
        for conf, true, pred, path, reason in mistakes[:10]:
            print(f"  [{conf:.2f}] true={'include' if true==1 else 'exclude'} "
                  f"pred={'include' if pred==1 else 'exclude'}  {path}")
            print(f"         reason: {reason}")


# ---------------------------------------------------------------------------
# Scoring (inference)
# ---------------------------------------------------------------------------

def cmd_score(model_path: str, top_k: int, threshold: float):
    """Read file paths from stdin, score them, print results sorted by score."""
    pipeline, _ = _load_model(model_path)

    paths = [line.strip() for line in sys.stdin if line.strip()]
    if not paths:
        print("No file paths received on stdin.", file=sys.stderr)
        sys.exit(1)

    X = [features_to_vector(extract_features(p)) for p in paths]
    probas = pipeline.predict_proba(X)[:, 1]

    scored = sorted(zip(probas, paths), reverse=True)

    if top_k:
        scored = scored[:top_k]

    print(f"{'score':>6}  path")
    print("-" * 60)
    for prob, path in scored:
        marker = "✅" if prob >= threshold else "  "
        print(f"{prob:>6.3f}  {marker} {path}")


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

def _load_model(model_path: str):
    if not Path(model_path).exists():
        print(f"❌ Model file not found: {model_path}", file=sys.stderr)
        sys.exit(1)
    with open(model_path, "rb") as f:
        data = pickle.load(f)
    return data["pipeline"], data.get("feature_columns", FEATURE_COLUMNS)


# ---------------------------------------------------------------------------
# Public API for use in collector.py
# ---------------------------------------------------------------------------

class FileScorer:
    """
    Thin wrapper around a trained ML model for use inside collector.py.

    Usage
    -----
    scorer = FileScorer.load("scorer.pkl")
    files = scorer.rank(["src/api.py", "tests/test_api.py", "README.md"])
    # files is a list of (score, path) sorted by score descending

    files_to_scan = scorer.filter("src/api.py", threshold=0.5)
    # returns True/False
    """

    def __init__(self, pipeline, feature_columns=None):
        self._pipeline = pipeline
        self._feature_columns = feature_columns or FEATURE_COLUMNS

    @classmethod
    def load(cls, model_path: str) -> "FileScorer":
        pipeline, feature_columns = _load_model(model_path)
        return cls(pipeline, feature_columns)

    def score(self, rel_path: str) -> float:
        """Return a probability score in [0, 1] for a single file path."""
        feats = features_to_vector(extract_features(rel_path))
        return float(self._pipeline.predict_proba([feats])[0][1])

    def rank(self, rel_paths: list[str]) -> list[tuple[float, str]]:
        """Score and rank a list of paths. Returns [(score, path), ...] descending."""
        X = [features_to_vector(extract_features(p)) for p in rel_paths]
        probas = self._pipeline.predict_proba(X)[:, 1]
        return sorted(zip(probas.tolist(), rel_paths), reverse=True)

    def filter(self, rel_path: str, threshold: float = 0.5) -> bool:
        """Return True if the file should be scanned."""
        return self.score(rel_path) >= threshold


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Train and use the ML file scorer")
    sub = parser.add_subparsers(dest="command", required=True)

    p_train = sub.add_parser("train", help="Train a model from JSONL training data")
    p_train.add_argument("--data",       required=True, help="Path to training_data.jsonl")
    p_train.add_argument("--model",      default="scorer.pkl", help="Output model file")
    p_train.add_argument("--test-split", type=float, default=0.2,
                         help="Fraction held out for evaluation (0 to skip)")

    p_eval = sub.add_parser("eval", help="Evaluate a saved model against a JSONL file")
    p_eval.add_argument("--data",  required=True, help="Path to evaluation JSONL")
    p_eval.add_argument("--model", default="scorer.pkl")

    p_score = sub.add_parser("score",
                              help="Score file paths from stdin using a saved model")
    p_score.add_argument("--model",     default="scorer.pkl")
    p_score.add_argument("--top-k",     type=int, default=0,
                         help="Only show top K results (0 = all)")
    p_score.add_argument("--threshold", type=float, default=0.5,
                         help="Score threshold for the include marker")

    args = parser.parse_args()

    if args.command == "train":
        cmd_train(args.data, args.model, args.test_split)
    elif args.command == "eval":
        cmd_eval(args.data, args.model)
    elif args.command == "score":
        cmd_score(args.model, args.top_k, args.threshold)


if __name__ == "__main__":
    main()
